{% set name = "robotframework-databaselibrary" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robotframework-databaselibrary-{{ version }}.tar.gz
  sha256: 4fb967b3e9b57475c0c21e351b2a01b1eafa8b923b865b3c9832d79d651f5c04

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0
    - robotframework
    - robotframework-excellib
    - pip
  run:
    - python >=3.7
    - robotframework
    - robotframework-excellib

test:
  imports:
    - DatabaseLibrary
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/franz-see/Robotframework-Database-Library
  summary: Database utility library for Robot Framework
  doc_url: https://pythonhosted.org/robotframework-databaselibrary/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
